### ISSUE TITLE
Implement change password functionality

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio-htpasswd#32]
It is a new feature and supports  https://github.com/verdaccio/verdaccio/issues/401.

**Comment by ashishsurana** [comment]
@ayusharma @juanpicado I want to work on this issue

**Comment by ayusharma** [comment]
Go ahead. All yours.

**Comment by juanpicado** [comment]
There is no endpoint yet

**Comment by juanpicado** [comment]
Unless this ticket is the task to create the endpoint 🤔
