### ISSUE TITLE
htpasswd bcrypt support

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio-htpasswd#4]
Refers to https://github.com/verdaccio/verdaccio/issues/191

**Comment by ajaybgupta** [comment]
@juanpicado @ayusharma Can you please let me know more about this issue? Would love to solve this.

**Comment by juanpicado** [comment]
@ajaybgupta https://github.com/verdaccio/verdaccio/issues/191

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/releases/tag/v3.0.0-beta.6
