### ISSUE TITLE
Existing user cannot login with max_users: -1

### ISSUE THREAD

**Issue by SystemParadox** [verdaccio/verdaccio-htpasswd#40]
According to the documentation, `max_users: -1` is supposed to disable new user registration. However, it also seems to prevent existing users from logging in.

`npm login --registry=http://[private url]` and `npm adduser --registry=http://[private url] --scope=@private --always-auth` both give the following:

```
npm ERR! 403 Forbidden - PUT http://npm.datacap.co.uk/-/user/org.couchdb.user:simon - maximum amount of users reached
```

The verdaccio log shows:

```
'PUT /-/user/org.couchdb.user:simon', error: maximum amount of users reached
```

The user is in the htpasswd file. Login works correctly without `max_users: -1`, even if the htpasswd file is read-only to verdaccio.

- verdaccio version: 3.10.2 (docker)
- verdaccio-htpasswd version: 0.2.2
- node version: 6.16.0
- npm version: 6.7.0

**Comment by alexjurkiewicz** [comment]
I've also run into this, and I've found a workaround.

Users can log into the web interface, and then npm login works fine!

Here is example workflow to replicate the issue.

1. Start verdaccio with following config:
```yaml
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Disable registration
    max_users: -1
```
2. Add user to htpasswd file. For example `test:$apr1$tnpH2JTI$vWBTITZOAYCg3SZlzPatu0` (password is `qwerty`)
3. Attempt to log in with `npm login --registry xxx`. Failure returned to client `Registry returned 403 for PUT on https://npm.test.kounta.com/-/user/org.couchdb.user:test: maximum amount of users reached` (also: I would prefer these error messages to not go through to clients). Verdaccio access log shows:
```
 http <-- 403, user: null(1.2.3.4 via 10.12.13.86), req: 'PUT /-/user/org.couchdb.user:test', error: maximum amount of users reached
 http <-- 403, user: null(1.2.3.4 via 10.12.13.86), req: 'PUT /-/user/org.couchdb.user:test', error: maximum amount of users reached
```
4. Visit web interface and log in. This succeeds and Verdaccio access log shows:
```
 http <-- 200, user: test(1.2.3.4 via 10.12.13.86), req: 'POST /-/verdaccio/login', bytes: 39/232
```
5. Re-try `npm` CLI login using the same command as before. Verdaccio access log shows:
```
 http <-- 409, user: null(1.2.3.4 via 10.12.13.86), req: 'PUT /-/user/org.couchdb.user:test', error: username is already registered
 http <-- 200, user: null(1.2.3.4 via 10.12.13.86), req: 'GET /-/user/org.couchdb.user:test?write=true', bytes: 0/53
 http <-- 201, user: test(1.2.3.4 via 10.12.13.86), req: 'PUT /-/user/org.couchdb.user:test/-rev/undefined', bytes: 170/85
```
6. It works!

**Comment by juanpicado** [comment]
I just tested on Verdaccio 4, works fine. We need to find the reason why is failing on Verdaccio 3.

**Comment by mikesi** [comment]
@alexjurkiewicz Another workaround is to set max_users to the number of your registered users.

**Comment by DanielRuf** [comment]
Do we still need a fix for v3?

**Comment by juanpicado** [comment]
Unless someone that does not want or cannot move to v4 and wants to investigate to fix it there, I'm fine, from my side, I am not interested to invest time in it.

**Comment by juanpicado** [comment]
It can be closed I guess.
