### ISSUE TITLE
where is the .htpasswd file?

### ISSUE THREAD

**Issue by flyon** [verdaccio/verdaccio-htpasswd#58]
This may be a silly question, but I cant figure it out somehow.

Where would one find or create the .htpasswd file?

I'm using pm2 to run verdaccio.

```
│ script path       │ /bin/verdaccio                      │
│ error log path    │ /root/.pm2/logs/verdaccio-error.log │
│ out log path      │ /root/.pm2/logs/verdaccio-out.log   │
│ pid path          │ /root/.pm2/pids/verdaccio-0.pid     │
│ exec cwd          │ /root    
```

would I create it in `/root/.htpasswd` ? (obviously I could change the exec cwd to something else but root)

**Comment by juanpicado** [comment]
I think here `/root/.config/verdaccio/htpasswd`.
